josefina17888/nomade

- README.md
> boilerfirst

- api/package.json
> Db conectada y modelos definidos

- api/app.js
- api/src/models/Booking.js
- api/src/routes/booking/booking.js
- api/src/routes/booking/controller.js
- api/src/routes/host/host.js
- api/src/routes/index.js
Agregué el bodyParser, también mi ruta POST pero sin relaciones, ya que no tengo aún sus modelos.
> Add ruta POST newBooking sin relacion

- api/src/routes/guestReview/guestReview.js
- api/src/routes/index.js
- api/src/routes/lodging/lodging.js
- api/src/routes/lodgingReview/lodgingReview.js
Chicos/as, ahi agregue en index de routes un par de rutas que no estaban llamadas y cada que hacía un pull las tenía que agregar.
Y en el segundo commit arme el get lodging filtrado por ciudad. 
En el tercer commit actualizamos las rutas de reviews.
> rutas agregadas al index

- client/package.json
- client/public/index.html
- client/src/App.js
- client/src/Redux/Store/index.js
- client/src/components/AllCards/AllCards.js
- client/src/components/CardDetail/CardDetail.js
- client/src/components/FormHost/FormHost.js
- client/src/components/FormUser/FormUser.js
- client/src/components/FormUser/FormUser.module.css
- client/src/components/GoogleMaps/GoogleMaps.js
- client/src/components/GoogleMaps/GoogleMaps.module.css
- client/src/components/Home/Home.js
- client/src/components/SearchBar/SearchBar.js
> Update Front-End Components, Map, UserLogin, redux and dependencies

- client/src/Redux/Actions/index.js
- client/src/Redux/Reducer/index.js
- client/src/Redux/Store/index.js
- client/src/components/AllCards/AllCards.js
- client/src/components/AllCards/AllCardsPaging/AllCardsPaging.js
- client/src/components/Card/Card.js
- client/src/components/Home/Home.js
- client/src/index.js
Provider, allcards y allcardspaging
> Jose all cards

- api/src/models/Guest.js
- api/src/models/Host.js
- api/src/routes/host/host.js
- api/src/routes/lodging/lodging.js
Corrección modelo Host
Corrección ruta post Host
Get Lodgings filtrado por City
> correccion en Host y postHost y get con filtro City

- api/src/routes/lodging/lodging.js
- client/src/components/AllCards/AllCards.js
- client/src/components/Card/Card.js
- client/src/components/Home/Home.js
actualización cambios en cors
cambios en cards
> actualizacionCorsyCards

- api/app.js
- api/src/routes/lodging/lodging.js
cors y arreglo en post lodging
> Jose nueva

- api/src/models/Lodging.js
- api/src/routes/guest/controller.js
- api/src/routes/guest/guest.js
- api/src/routes/lodging/lodging.js
Cambios en modelo Lodging 
Cambios en ruta guest
Cambios en ruta lodging
Todo para funcionamiento de carga de imagenes
> Cambios imagenes

- client/src/Redux/Actions/index.js
- client/src/Redux/Reducer/index.js
- client/src/components/AllCards/AllCards.js
- client/src/components/AllCards/AllCards.module.css
- client/src/components/Card/Card.js
Cambié muy poco estilos y creé el ordenamiento por precio.
> ordenamiento por precio

- client/src/App.js
- client/src/Redux/Actions/index.js
- client/src/Redux/Reducer/index.js
- client/src/components/AllCards/AllCards.js
- client/src/components/CardDetail/CardDetail.js
Armado de pantalla details a mitad camino, falta ruta back
> Detailsmitadcamino

- api/src/models/Host.js
- api/src/routes/host/host.js
- client/src/Redux/Actions/index.js
Adición ruta put host
Cambio ruta post host para imagen dni
Action de post host en front
> actualización ruta post host, adicion put host, action de postHost

- api/src/routes/host/host.js
- api/src/routes/lodging/lodging.js
- client/src/App.js
- client/src/Redux/Actions/index.js
- client/src/Redux/Reducer/index.js
- client/src/components/CardDetail/CardDetail.js
- client/src/components/FormHost/FormHost.js
> cambios en card detail

- client/src/components/FormGuest/FormGuest.js
> cambios en form

- client/src/components/LoginUser/LoginUser.js
> cambios en login

- api/src/models/Guest.js
- api/src/routes/guest/guest.js
- client/src/Redux/Actions/index.js
- client/src/Redux/Reducer/index.js
- client/src/components/FormGuest/FormGuest.js
- client/src/components/FormGuest/FormUser.module.css
- client/src/components/FormGuest/validation.js
formulario controlado de Guest, todavia no esta terminado
> Formulario controlado de Guest

- api/src/routes/host/host.js
- client/src/components/FormLodging/FormLodging.js
> cambios host id

- api/src/routes/guest/guest.js
- api/src/routes/host/host.js
- api/src/routes/lodging/lodging.js
> cambios redirects

- api/src/routes/lodgingReview/lodgingReview.js
- client/src/App.js
- client/src/components/CardDetail/CardDetail.js
- client/src/components/FormLodging/FormLodging.js
- client/src/components/LodgingReview/LodgingReview.js
- client/src/components/LodgingReview/validate.js
lodging review anda y valida, añadido al componente detail (debatir)
> Brunobranch

- client/src/components/FormHost/FormHost.js
> arreglo form Host

- client/src/components/Menu/Menu.js
> icono rating

- client/src/components/Booking/Booking.js
> arreglo mp

- client/src/components/LoginUser/LoginUser.jsx
Cambios en el componente Login User
> Update component loginuser

- api/src/models/Booking.js
- api/src/routes/booking/booking.js
- client/src/components/Booking/Booking.js
- client/src/components/Card/Card.js
- client/src/components/Home/Home.js
- client/src/components/MercadoPago/Status.js
- client/src/components/Messenger/Chat/Chat.js
- client/src/index.js
Comprobación en Back y modificación en React.StrictMode
> Ya funciona un solo posteo

- client/src/components/Messenger/Chat/Chat.js
- client/src/components/Messenger/Chat/Chat.module.css
> cambios en css
